AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TestWatchServerless
Globals:
  Function:
    Timeout: 3


Resources:

  HelloWorldFunction1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda1
      Handler: app.lambda_handler
      Runtime: python3.6
      Environment:
        Variables:
          TARGET_LAMBDA_FUNCTION: !Ref HelloWorldFunction2
      Policies:
        LambdaInvokePolicy:
          FunctionName: !Ref HelloWorldFunction2
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  HelloWorldFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda2
      Handler: app.lambda_handler
      Runtime: python3.6

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

