swagger: "2.0"
info:
  description: "SwaggerとAPI Gatewayのサンプルです。"
  version: "1.0.0"
  title: "Test Watch Serverless API"
basePath: "/Prod"
schemes:
  - "https"
paths:
  /hello:
    get:
      tags:
        - "Hello"
      summary: "This is summary"
      description: "This is description"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction1.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
definitions:
  Hello:
    type: "object"
    required:
      - "message"
    properties:
      message:
        type: "string"